<?php

namespace EinscriptionBundle\Repository;

/**
 * Annee_AcademiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Annee_AcademiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
