<?php

namespace EinscriptionBundle\Repository;

/**
 * CorrespondantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorrespondantRepository extends \Doctrine\ORM\EntityRepository
{
}
