<?php

namespace EinscriptionBundle\Repository;

/**
 * Frais_InscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Frais_InscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
